type InsightsPanelProps = {
  insights: string[];
  revenue: number;
  expenses: number;
  profit: number;
};

export default function InsightsPanel({
  insights,
  revenue,
  expenses,
  profit,
}: InsightsPanelProps) {
  const expenseRatio =
    revenue > 0 ? (expenses / revenue) * 100 : 0;

  const profitMargin =
    revenue > 0 ? (profit / revenue) * 100 : 0;

  let recommendation =
    "Continue monitoring your financial performance.";

  if (profit < 0) {
    recommendation =
      "Your expenses exceed revenue. Review major cost categories immediately.";
  } else if (expenseRatio > 80) {
    recommendation =
      "Expenses are consuming most of your revenue. Consider reducing operating costs.";
  } else if (profitMargin < 15) {
    recommendation =
      "Profit margin is relatively low. Review pricing and cost efficiency.";
  } else if (profitMargin >= 40) {
    recommendation =
      "Profit margin is strong. Maintain cost discipline and monitor future growth.";
  }
let healthStatus = "Healthy";
let healthStyle = "bg-green-500/10 text-green-400 border-green-500/30";

if (profit < 0) {
  healthStatus = "Critical";
  healthStyle = "bg-red-500/10 text-red-400 border-red-500/30";
} else if (profitMargin < 15 || expenseRatio > 80) {
  healthStatus = "Warning";
  healthStyle = "bg-yellow-500/10 text-yellow-400 border-yellow-500/30";
}
  return (
    <div className="mt-8 rounded-xl border border-zinc-700 bg-zinc-900 p-6">
      <div className="mb-6">
        <h2 className="text-2xl font-bold text-white">
          🤖 LedgerAI Analyst
        </h2>

        <p className="mt-1 text-zinc-400">
  Automatic financial analysis generated by LedgerAI
</p>

<div
  className={`mt-4 inline-flex items-center rounded-full border px-4 py-2 text-sm font-semibold ${healthStyle}`}
>
  Financial Health: {healthStatus}
</div>
      </div>

      <div className="space-y-4">
        {insights.map((insight, index) => (
          <div
            key={index}
            className="rounded-xl border border-zinc-800 bg-zinc-950 p-5"
          >
            <p className="mb-2 text-sm text-zinc-500">
              Observation #{index + 1}
            </p>

            <p className="text-lg text-green-400">
              {insight}
            </p>
          </div>
        ))}
      </div>

      <div className="mt-6 rounded-xl border border-zinc-800 bg-zinc-950 p-5">
        <p
  className={`font-semibold ${
    profit < 0
      ? "text-red-400"
      : profitMargin < 15
      ? "text-yellow-400"
      : "text-green-400"
  }`}
>
  💡 Recommendation
</p>

        <p className="mt-2 text-zinc-300">
          {recommendation}
        </p>
      </div>
    </div>
  );
}